### ISSUE TITLE
Error "ViewerUI is not a constructor" when starting the viewer

### ISSUE THREAD

**Issue by HDinger** [xeokit/xeokit-viewer#27]
With the latest version 1.4.1, the following code does not work any more with this error: `ViewerUI is not a constructor`. 

```
const viewerUI = new ViewerUI(server, {
    //...
});
```

This is because [this class](https://github.com/xeokit/xeokit-viewer/blob/master/src/ViewerUI.js#L8) is intended to ensure backwards compatibility, but is not part of the compressed `dist/main.js`. 
Using `const viewerUI = new BIMViewer(server, {});` works however.

**Comment by HDinger** [comment]
@xeolabs This is just a minor issue I stumbled over when updating the viewer within OpenProject. However, as it works fine with `new BIMViewer(server, {});` this is no showstopper.

**Comment by xeolabs** [comment]
Cool - can I now just rename ````ViewerUI```` to ````BIMViewer````?

**Comment by HDinger** [comment]
That is fine for us 👍
